# This is the network config written by 'subiquity'
network:
  ethernets:
    ens160:
      dhcp4: no
      addresses:
              - 172.16.1.151/24
      gateway4: 172.16.1.2
      nameservers: 
          search: [group3.local]
          addresses: [172.16.1.12, 172.16.1.13]
  version: 2
  renderer: networkd
