--- 
- name: create user on docker/centos machines
  hosts: ubuntu:centos
  become: true
  tasks:
   - name: creating account with password called ansible
     user:
       name: ansible
       comment: account created with ansible
       password: '$6$7iZgELMS8NrL$LzhRhM8Jye7l3YG7CzfB40m02tPkiFoG7VClYFEjMO3Tdgpbmy.Q17BbmpNBnUrUD9bkqDChRClLrlhJg0IkU/'
